Repository mlr-org/mlr3, pull requests merged in 2018-12, with the labels that each got.

#85 update train-predict vignette
  docs/articles/basic-02-train-predict-score.html
  docs/reference/BenchmarkResult.html
  docs/reference/Experiment.html
  docs/reference/Log.html
  docs/reference/ResampleResult.html
  docs/reference/Resampling.html
  vignettes/basic-02-train-predict-score.Rmd
Labels: Status: In Progress

#92 Update and rename resample/benchmarking vignette
  vignettes/basic-03-resample-benchmarking.Rmd
Labels: Priority: Low, Type: Documentation

#86 Update Task.R
  R/Task.R
  docs/articles/basic-01-tasks.html
  man/Task.Rd
  vignettes/basic-01-tasks.Rmd
Labels: Priority: Medium, Status: In Progress, Type: Documentation
